services:
  photo-log:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8228:8228"
    volumes:
      - ../src/client/uploads:/photo-log/src/client/uploads
      - ../data:/photo-log/data
      - ../logs:/photo-log/logs
    environment:
      - DB_PATH=/photo-log/data/photo_log.db
      - ADMINPASS=${ADMINPASS}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production
      - WIDGET_ALLOWED_ORIGINS=${WIDGET_ALLOWED_ORIGINS}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8228/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
